# load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "app",
    srcs = glob(["src/main/java/**/*.java"]),
    main_class = "ch.vorburger.learniningbazel.Main",
    deps = ["//lib"]
)
